# Generated by Django 4.2.4 on 2023-09-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DR', 'ВОДИТЕЛЬ'), ('LT', 'ЛОГИСТ')], default='DR', max_length=2, verbose_name='Роль'),
        ),
    ]
