# Generated by Django 4.2.4 on 2023-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Exbot', '0005_remove_point_arrive_remove_point_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('SLEEP', 'СПИТ'), ('AWAKE', 'ПРОСНУЛСЯ'), ('ONROAD', 'В ДОРОГЕ'), ('ARRIVED', 'ПРИБЫЛ')], default='SLEEP', max_length=20, verbose_name='Статус'),
        ),
    ]
